### ISSUE TITLE
неудобное управление и интерфейс 

### ISSUE THREAD

**Issue by Yblidok** [vangers-app/vss#2]
управление движение не очень интуитивно  предлагаю стик разделить на 4 равных части все мелкое курсор не совпадает с местом клика при абузе через нимбос ломается магазин модельки при покупке через этот баг не меняются и прозьба сделать в настройках  кастомизацию управления как в терарии чтоб можно было удалять добавлять элементы и двигать их местами и изменять размер

**Comment by caiiiycuk** [comment]
Версия 1.0.3
